"""Geometry asset, meshing, and voxelization helpers for backend lowering."""

from ._mesh_targets import (
    ResolvedAirboxTarget,
    ResolvedObjectPreviewTarget,
    ResolvedSharedDomainTargets,
    ResolvedSharedObjectTarget,
    SharedDomainBuildReport,
    resolve_object_preview_target,
    resolve_shared_domain_targets,
)
from .asset_pipeline import (
    realize_fdm_grid_asset,
    realize_fem_domain_mesh_asset,
    realize_fem_domain_mesh_asset_from_components,
    realize_fem_mesh_asset,
)
from .gmsh_bridge import (
    MESH_SIZE_CALIBRATIONS,
    MESH_SIZE_PRESETS,
    AirboxOptions,
    ComponentDescriptor,
    MeshData,
    MeshOptions,
    MeshQualityReport,
    SharedDomainMeshResult,
    SizeFieldData,
    add_air_box,
    extract_per_domain_quality,
    generate_box_mesh,
    generate_cylinder_mesh,
    generate_difference_mesh,
    generate_mesh,
    generate_mesh_from_file,
    generate_shared_domain_mesh_from_components,
    remesh_with_size_field,
    resolve_mesh_size_controls,
)
from .quality import MeshValidationReport, validate_mesh
from .surface_assets import SurfaceAsset, export_geometry_to_stl, load_surface_asset
from .voxelization import VoxelMaskData, voxelize_geometry

__all__ = [
    "MESH_SIZE_CALIBRATIONS",
    "MESH_SIZE_PRESETS",
    "AirboxOptions",
    "ComponentDescriptor",
    "MeshData",
    "MeshOptions",
    "MeshQualityReport",
    "MeshValidationReport",
    "SharedDomainMeshResult",
    "SizeFieldData",
    "SurfaceAsset",
    "VoxelMaskData",
    "add_air_box",
    "export_geometry_to_stl",
    "extract_per_domain_quality",
    "generate_box_mesh",
    "generate_cylinder_mesh",
    "generate_difference_mesh",
    "generate_mesh",
    "generate_mesh_from_file",
    "generate_shared_domain_mesh_from_components",
    "load_surface_asset",
    "ResolvedAirboxTarget",
    "ResolvedObjectPreviewTarget",
    "ResolvedSharedDomainTargets",
    "ResolvedSharedObjectTarget",
    "SharedDomainBuildReport",
    "resolve_object_preview_target",
    "resolve_shared_domain_targets",
    "realize_fdm_grid_asset",
    "realize_fem_domain_mesh_asset",
    "realize_fem_domain_mesh_asset_from_components",
    "realize_fem_mesh_asset",
    "remesh_with_size_field",
    "resolve_mesh_size_controls",
    "validate_mesh",
    "voxelize_geometry",
]
