"""Public embedded Python DSL for Fullmag."""

from . import init
from .init import random, uniform
from .model import (
    AdaptiveTimestep,
    Box,
    DeviceTarget,
    Cylinder,
    Demag,
    Difference,
    DiscretizationHints,
    Ellipse,
    Ellipsoid,
    Exchange,
    ExecutionMode,
    ExecutionPrecision,
    FDM,
    FDMDemag,
    FDMGrid,
    FEM,
    Ferromagnet,
    Hybrid,
    ImportedGeometry,
    Intersection,
    InterfacialDMI,
    LLG,
    Material,
    Problem,
    Region,
    Relaxation,
    RuntimeSelection,
    SaveField,
    SaveScalar,
    Snapshot,
    Sphere,
    TimeEvolution,
    Translate,
    Union,
    Zeeman,
    backend,
)
from .runtime import BackendTarget, Result, Simulation, load_problem_from_script
from .meshing import (
    MeshData,
    MeshOptions,
    MeshQualityReport,
    generate_mesh,
    export_geometry_to_stl as export_stl,
)

# ── Flat scripting API (mumax-style) ──────────────────────
from .world import (
    GeometryMeshHandle,
    MagnetHandle,
    build_mesh,
    boundary_correction,
    name,
    engine,
    device,
    cell,
    mesh,
    hmax,
    fem_order,
    interactive,
    geometry,
    solver,
    b_ext,
    save,
    snapshot,
    tableautosave,
    name as set_name,
    run,
    relax,
    reset,
)

__all__ = [
    # Class-based API
    "BackendTarget",
    "AdaptiveTimestep",
    "Box",
    "Cylinder",
    "Demag",
    "DeviceTarget",
    "Difference",
    "DiscretizationHints",
    "Ellipse",
    "Ellipsoid",
    "Exchange",
    "ExecutionMode",
    "ExecutionPrecision",
    "FDM",
    "FDMDemag",
    "FDMGrid",
    "FEM",
    "Ferromagnet",
    "Hybrid",
    "ImportedGeometry",
    "Intersection",
    "InterfacialDMI",
    "LLG",
    "Material",
    "MeshData",
    "Problem",
    "Region",
    "Relaxation",
    "Result",
    "RuntimeSelection",
    "SaveField",
    "SaveScalar",
    "Snapshot",
    "Simulation",
    "Sphere",
    "TimeEvolution",
    "Translate",
    "Union",
    "Zeeman",
    "backend",
    "export_stl",
    "generate_mesh",
    "init",
    "load_problem_from_script",
    "random",
    "uniform",
    # Flat scripting API
    "GeometryMeshHandle",
    "MagnetHandle",
    "build_mesh",
    "boundary_correction",
    "name",
    "engine",
    "device",
    "cell",
    "mesh",
    "hmax",
    "fem_order",
    "interactive",
    "geometry",
    "solver",
    "b_ext",
    "save",
    "snapshot",
    "tableautosave",
    "set_name",
    "run",
    "relax",
    "reset",
]
