"""Public embedded Python DSL for Fullmag."""

from . import init
from .init import random, uniform
from .model import (
    Box,
    Cylinder,
    Demag,
    DiscretizationHints,
    Exchange,
    ExecutionMode,
    ExecutionPrecision,
    FDM,
    FEM,
    Ferromagnet,
    Hybrid,
    ImportedGeometry,
    InterfacialDMI,
    LLG,
    Material,
    Problem,
    Region,
    SaveField,
    SaveScalar,
    TimeEvolution,
    Zeeman,
)
from .runtime import BackendTarget, Result, Simulation, load_problem_from_script

__all__ = [
    "BackendTarget",
    "Box",
    "Cylinder",
    "Demag",
    "DiscretizationHints",
    "Exchange",
    "ExecutionMode",
    "ExecutionPrecision",
    "FDM",
    "FEM",
    "Ferromagnet",
    "Hybrid",
    "ImportedGeometry",
    "InterfacialDMI",
    "LLG",
    "Material",
    "Problem",
    "Region",
    "Result",
    "SaveField",
    "SaveScalar",
    "Simulation",
    "TimeEvolution",
    "Zeeman",
    "init",
    "load_problem_from_script",
    "random",
    "uniform",
]
